# -*- coding: utf-8 -*-
"""CNN_MNIST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LdWgwSQQSWda4txyVFw9U7C7FLej4oMo
"""

import tensorflow as tf

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train.shape,x_test.shape

x_train = x_train/255.0
x_test = x_test/255.0
y_train, y_test = tf.keras.utils.to_categorical(y_train), tf.keras.utils.to_categorical(y_test)



x_train = x_train.reshape(60000,28,28,1)
x_test = x_test.reshape(10000,28,28,1)

x_train.shape

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(32,(3,3),input_shape = (28,28,1),activation='relu'))
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2,2)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(50,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))

model.summary()

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,batch_size=32,epochs=10,validation_data=(x_test,y_test))

import cv2

img = cv2.imread('i8.jpg')

img.shape

import matplotlib.pyplot as plt

img8 = cv2.resize(img,(28,28))

img8.shape

plt.imshow(img8[:,:,0])

img8[:,:,0].shape

img8[:,:,0]

img8_1 = cv2.invert(img8)
img8_1[:,:,0]

img8 = img8[:,:,0].reshape(28,28,1)

img8 = img8/255.0

img8

model.predict(img8.reshape(1,28,28,1)).argmax()

