# -*- coding: utf-8 -*-
"""Tensorflow(1.x).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1usBXNYOHm7DyXizZ7qP5qQ0dekME6zd5
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 1.x
import tensorflow as tf

c1 = tf.constant(3.14,name="MyConst")

c1.name

v1 = tf.Variable(123)

v1

p1 = tf.placeholder(dtype=tf.float32)

p1

sess = tf.Session()
sess.run(c1)

init = tf.global_variables_initializer()
sess.run(init)

sess.run(v1)

p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)

y = tf.add(p1,p2)

sess = tf.Session()
sess.run(y,feed_dict={p1:10,p2:20})

x = tf.placeholder(tf.float32)
w = tf.Variable(5.0)
b = tf.Variable(10.0)
#y = 3x+10 equation 
y = tf.add(tf.multiply(x,w),b)
init = tf.global_variables_initializer()
sess.run(init)
sess.run(y,feed_dict={x:5})

x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
b = tf.Variable(2.0)
# m = (x+y)b
m = tf.multiply(tf.add(x,y),b)
init = tf.global_variables_initializer()
sess.run(init)
sess.run(m,feed_dict={x:2.0,y:3.0})

